### ISSUE TITLE
Only working on page refresh

### ISSUE THREAD

**Issue by StefanCov** [samie/vaadin-ga-tracker#18]
Hi, I have managed to get some data sent back to Google Analytics but that only seems to be when a page is refreshed. I have added a GoogleAnalyticsTracker.getCurrent().sendEvent() to a afterNavigationEvent(). The page view would already get picked up with a page refresh anyway but the event is only sent back once I refresh the page and not when I navigate normally. This is weird as the method is called when I navigate to the page without a refresh. Is getCurrent() not likely to work without a refresh?

**Comment by samie** [comment]
Hi, just to make sure first: which version is this?

**Comment by StefanCov** [comment]
Hi, this is version 4.0.0 of googleanalyticstracker

**Comment by Legioth** [comment]
The add-on has an automatically registered `AfterNavigationListener` which is supposed to send an event for every navigation.

There are, however, two different conditions that can cause the event to not be sent:
1. The view or any of its parent layouts is annotated with `@IgnorePageView`.
2. The tracker isn't already configured, and it cannot configure itself because the top-level router layout isn't either annotated with `@EnableGoogleAnalytics` or implementing `TrackerConfigurator`.

It would helpful if you could put a breakpoint in `InitListener.shouldTrack` to first verify that it is actually called, and then check whether it returns `false` and in that case why?

**Comment by StefanCov** [comment]
It seems that the `@EnableGoogleAnalytics` works as intended when hosted on a Tomcat Server. This is weird as it doesn't work as intended on my local Tomcat. It makes developing a little hard for now as I cannot test the code before it goes live.

**Comment by samie** [comment]
Localhost testing used to have some limitation with cookie domain setting. Don't remember what is the default now, but setting cookieDomain to `auto` or `none` should help.
https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#automatic_cookie_domain_configuration

**Comment by Legioth** [comment]
Did you notice that the default configuration doesn't actually send anything to Google Analytics when production mode is disabled, but instead only prints the data that would be sent to the browser console? You can change this by adding `sendMode = SendMode.ALWAYS` to `@ EnableGoogleAnalytics`.

Otherwise, it would be useful if you could try debugging with the breakpoint I suggested to help further poinpoint the cause of this issue.

**Comment by StefanCov** [comment]
@Legioth Sorry I have not had much time to work on this. I can't currently set a breakpoint within the googleanalyticstracker-4.0.0.jar on InitListener as it is a .class file. I have now come across another problem when upgrading to Vaadin 14.1 which I have made an issue for https://github.com/samie/vaadin-ga-tracker/issues/19. I don't see any changes from 14.0 to 14.1 which would break the google analytics tracker.

**Comment by Legioth** [comment]
> I can't currently set a breakpoint within the googleanalyticstracker-4.0.0.jar on InitListener as it is a .class file.

It should be possible after you have instructed your IDE to download the sources using Maven.
