### ISSUE TITLE
Broken on Vaadin 14.1.3

### ISSUE THREAD

**Issue by StefanCov** [samie/vaadin-ga-tracker#19]
I used @EnableGoogleAnalytics with Vaadin 14.0.2 and it all works perfectly. I have now upgraded to Vaadin 14.1.3 and it no longer works at all. Nothing is sent back to Google Analytics and the Google Tag extension finds the tracker code but complains about a HTTP response. I don't 100% know what 14.1 would have released to break this. Any ideas what could have broken this?

**Comment by Legioth** [comment]
I tried running the [demo project](https://github.com/samie/vaadin-ga-tracker/tree/master/demo) using Vaadin 14.1.3 and everything seemed to work as expected in that case, except that I had to update the demo project's Jetty plugin to work with the newer ByteBuddy version. I'm also not aware of any changes between those versions that would have any direct impact on this add-on.

I would thus need some additional information to be able to help you with this problem. What exactly is the message in the complaint about the HTTP response? Do you see information about what should be tracked in the browser's console if you run with debug output enabled? The client-side debug logging is enabled by default when Vaadin is not in production mode, otherwise it's configurable by setting `productionLogging = LogLevel.DEBUG` in the `@EnableGoogleAnalytics` annotation.

**Comment by StefanCov** [comment]
@Legioth Hmm, that is weird how you're getting a different result. The message was from the Google Tag extension. Its just checks to see if you have attached the tracking code correctly and it said it was but I think the HTTP error was just a generic response. 

When I run the project on Vaadin 14.0 I get some extra resources in the Network Tab within my browser:
![image](https://user-images.githubusercontent.com/54804121/72420904-68f8e780-3777-11ea-82eb-e69fac8e0eaa.png)
![image](https://user-images.githubusercontent.com/54804121/72420928-74e4a980-3777-11ea-82c0-257659e7e7dd.png)

I do not get these with 14.1.3.

When I use the LogLevel.TRACE I get the same output in the console for each version which is:
![image](https://user-images.githubusercontent.com/54804121/72421116-d4db5000-3777-11ea-827c-749fc24912bd.png)

I have put a breakpoint at the InitListener.shouldTrack(), it runs and does not return false.

**Comment by StefanCov** [comment]
The Google Tag Assistant response
![image](https://user-images.githubusercontent.com/54804121/72422393-45836c00-377a-11ea-8db3-8961f6268732.png)

**Comment by StefanCov** [comment]
Ah, I have found out the other tag is an old tag but it seems to be working. I may try remove that or use the tag that way but I think it is an old implementation of ga.

**Comment by StefanCov** [comment]
I believe I have found the issue. The old implementation must have been conflicting with the @EnableGoogleAnalytics. The old version was all done within javascript which is why I couldn't find it. The multiple implementation worked within 4.0 but something must have changed in 4.1 which broke this.
